### ISSUE TITLE
Notice: Undefined index: prune_enable

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#4]
While the main is down with A 50X error occurred message, I wanted to place this here so I didn't lose track. I may have already placed it on the main site (?).

When creating a forum, if I do not tick the auto prune check box and I submit to create the forum, I get:

Notice: Undefined index: prune_enable in C:\xxxxx\xxx\xxxxxxxxxx\admin\admin_forums.php on line 404 

If I check the box to auto prune, there is no error at all. On a side note, this happened before AND after installing the portal. So it is a board issue not a portal issue.

**Comment by IntegraMOD** [comment]
Sorry Ray. If anyone ever considers A2hosting as a viable webhost I would say absolutely NOT! I chose them because server specs seemed pretty good for the price as AWS cost was spiraling out of control. My A2hosting account comes with a Webuzo control panel. It is extremely slow but pretty user friendly. The problem is that 38 hours ago I was locked out of the control panel with a message that my Webuzo licence had expired. Webuzo is free to me with this hosting plan and the plan is less than one month old. After a few wasted hours talking with A2hosting tech support and 38+ hours waiting for a resolution I have concluded that they have no clue what they are doing. I gave them root ssh login 38 hours ago and nobody has even logged into the server.

**Comment by IntegraMOD** [comment]
I updated admin_forums.php
I probably have a few more edits to upload as well.

**Comment by MWE001** [comment]
Not a problem at all. And that was one of the files I worked on as well. I am working on admin_db_utilities as we speak.

I just figured in the mean time I would start dropping issues here because I know me all to well. I will add fixes in stuff and totally forget what I did. So it is just as easy for me to add a fix and send a commit with git desktop at that point. 

And thanks for the heads up on that host. I can see a few hours here or there but 38? Yikes! That is down right nuts to treat paying clients that way.

**Comment by IntegraMOD** [comment]
I got phpbb2x.com back online. Its using the same php8.3.9 as integramod.com so Im not sure why integramod is still showing the 50x error since that error means php is not running but im going to stay off ssh until webuzo tech finishes so we dont cause a conflict.

**Comment by MWE001** [comment]
The only error I am getting now is the:

> Warning: Undefined array key "prune_enable" in C:\xxxxxxx\xxxxxx\xxxxxxl\admin\admin_forums.php on line 443

Now the only time I get this error is if the forum is already created **without** auto prune and I decide at a later time to move it to another category. On move, I get the above error. Previously the error showed up on forum creation.

**Comment by IntegraMOD** [comment]
try this for line 443

`				SET forum_name = '" . str_replace("\'", "''", $HTTP_POST_VARS['forumname']) . "', cat_id = " . intval($HTTP_POST_VARS[POST_CAT_URL]) . ", forum_desc = '" . str_replace("\'", "''", $HTTP_POST_VARS['forumdesc']) . "', forum_status = " . intval($HTTP_POST_VARS['forumstatus']) . ", prune_enable = " . intval($HTTP_POST_VARS['prune_enable'] ?? '') . "
`

not tested but should work

**Comment by MWE001** [comment]
That was the fix. Nice!

We can close this one out. You want to commit that one or do you need me to?

**Comment by IntegraMOD** [comment]
its in my git files already

**Comment by MWE001** [comment]
Right on. We should be good to go then. The fix worked like a charm. We should be able to safely close this one out if you are happy with it.

**Comment by IntegraMOD** [comment]
cool
